<a href="https://colab.research.google.com/github/hmmnyamminji/bootcampproject/blob/main/SubWay_seoul_fes_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 드라이브에 저장된 폰트 등록
import matplotlib as mpl
import matplotlib.pyplot as plt # 그래프를 그리는 모듈
import matplotlib.font_manager as fm # 폰트를 관리하는 모듈

# 드라이브 내 폰트 경로
font_path = '/content/drive/MyDrive/kwu/sub_project/font/NanumGothic.ttf'

fm.fontManager.addfont(font_path)
mpl.rc('font', family='NanumGothic') # matplotlib 기본 폰트로 설정
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['font.sans-serif'] = ['NanumGothic', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False # 마이너스(-) 기호가 깨지지 않도록 유니코드 마이너스 비활성화

print("현재 폰트: ", plt.rcParams['font.family']) # 현재 적용된 폰트 이름 출력

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
현재 폰트:  ['NanumGothic']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import xml.etree.ElementTree as ET
import warnings # 코드 실행 중 발생하는 불필요한 경고 메시지를 숨김
warnings.filterwarnings('ignore')
import pprint
from sklearn.linear_model import LinearRegression

서울시 문화행사 정보

In [ ]:
# https://data.seoul.go.kr/dataList/OA-15486/S/1/datasetView.do

In [ ]:
import requests
import pandas as pd

API_KEY = "696c51614b67696d3736727678634c"
SERVICE_NAME = "culturalEventInfo"

url = f"http://openapi.seoul.go.kr:8088/{API_KEY}/json/{SERVICE_NAME}/1/100/"

response = requests.get(url, timeout=10)
response.raise_for_status()

data = response.json()
df = pd.DataFrame(data['culturalEventInfo']['row'])

df.replace(0, np.nan, inplace=True)
df.fillna(method='ffill', inplace=True)
df

,CODENAME,GUNAME,TITLE,DATE,PLACE,ORG_NAME,USE_TRGT,USE_FEE,INQUIRY,PLAYER,...,RGSTDATE,TICKET,STRTDATE,END_DATE,THEMECODE,LOT,LAT,IS_FREE,HMPG_ADDR,PRO_TIME
0,전시/미술,강남구,2026 핸드아티코리아,2026-08-13~2026-08-16,코엑스전시장 B홀,기타,누구나,"정가 15,000원",02-6121-6233,,...,2026-02-06,시민,2026-08-13 00:00:00.0,2026-08-16 00:00:00.0,기타,127.059159043842,37.5118239121138,무료,https://culture.seoul.go.kr/culture/culture/cu...,10:00 ~ 18:00 (입장마감 17:30)
1,전시/미술,강남구,해외바이어가 직접 찾는 글로벌 전시회 [2026 인터참코리아] InterCHARM ...,2026-07-01~2026-07-03,"코엑스 A홀, C홀",기타,뷰티산업 종사자,"현장등록: 20,000원 (사전 등록 시, 무료 입장 가능)",070-5095-9904 / 9903,,...,2026-01-20,시민,2026-07-01 00:00:00.0,2026-07-03 00:00:00.0,기타,127.059159043842,37.5118239121138,유료,https://culture.seoul.go.kr/culture/culture/cu...,10:00~17:00
2,클래식,강남구,[GS아트센터] 양인모 X 김치앤칩스,2026-06-30~2026-06-30,GS아트센터,기타,7세 이상 (2019년생 포함 이전 출생자),"R 11만원, S 8만원, A 5만원",02-2005-0101,,...,2026-02-12,시민,2026-06-30 00:00:00.0,2026-06-30 00:00:00.0,기타,127.037336400239,37.5019949322814,유료,https://culture.seoul.go.kr/culture/culture/cu...,19:30
3,무용,강남구,[GS아트센터] NDT 1 - 필름 스크리닝 [미스트],2026-06-28~2026-06-28,GS아트센터,기타,14세 이상 (2012년생 포함 이전 출생자),"전석 20,000",02-2005-0101,,...,2026-02-12,시민,2026-06-28 00:00:00.0,2026-06-28 00:00:00.0,기타,127.037336400239,37.5019949322814,유료,https://culture.seoul.go.kr/culture/culture/cu...,17:00
4,무용,강남구,[GS아트센터] 다미앵 잘레 X 코헤이 나와 [프리즘],2026-06-28~2026-06-28,GS아트센터,기타,14세 이상 (2012년생 포함 이전 출생자),"전석 50,000원",02-2005-0101,,...,2026-02-12,시민,2026-06-28 00:00:00.0,2026-06-28 00:00:00.0,기타,127.037336400239,37.5019949322814,유료,https://culture.seoul.go.kr/culture/culture/cu...,15:00 / 19:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,교육/체험,종로구,"2026년 봄 궁중문화축전 [경복궁, 시간여행-궁중새내기]",2026-04-25~2026-04-29,경복궁 일대,기타,13세 이상(2013년 이전 출생자),"10,000원(1인 최대 4매 예매 가능)",프로그램 문의 1522-2295 | 티켓문의 1588-7890,,...,2026-04-10,기관,2026-04-25 00:00:00.0,2026-04-29 00:00:00.0,기타,126.976842133821,37.5759040910202,유료,https://culture.seoul.go.kr/culture/culture/cu...,(1회차) 10:00~12:30 | (2회차) 13:30~16:00
96,연극,노원구,[노원문화재단] 2026 노원어린이극장 공동기획 더 어린 관객을 위한 극장 [흔들흔...,2026-04-25~2026-04-26,노원어린이극장,노원문화재단,"임산부, 0~24개월 및 보호자","가족당 30,000원",02-2289-3452,극단 마실,...,2026-03-26,기관,2026-04-25 00:00:00.0,2026-04-26 00:00:00.0,어린이/청소년 문화행사,127.063692307584,37.6544500497108,유료,https://culture.seoul.go.kr/culture/culture/cu...,"11:00, 14:00 (사전워크숍 4월 24일 (금) 10:30)"
97,축제-기타,광진구,컴온러너스 런페스타 with 커먼그라운드,2026-04-25~2026-04-26,커먼그라운드 야외광장·MH동 1층 중앙팝업,기타,"누구나(입장의 경우 전연령 가능하나, 주류 구입은 성인에 한정)",,02-467-2747,,...,2026-03-31,시민,2026-04-25 00:00:00.0,2026-04-26 00:00:00.0,기타,127.065669226745,37.5410566332301,무료,https://culture.seoul.go.kr/culture/culture/cu...,9:00 ~ 19:00
98,축제-자연/경관,강서구,[서울식물원] 2026 서울식물원 해봄축제,2026-04-25~2026-04-26,서울식물원 열린숲 일대,서울식물원,누구나,무료,02-2104-9782,,...,2026-03-26,기관,2026-04-25 00:00:00.0,2026-04-26 00:00:00.0,기타,126.83500723721524,37.569657094189104,무료,https://culture.seoul.go.kr/culture/culture/cu...,토 - 일 11:00 ~ 19:00
99,클래식,서초구,[서초문화재단] 2026 서리풀 작곡가 탐구 시리즈 [고향에서 세계로 : 드보르작의...,2026-04-25~2026-04-25,반포심산아트홀,서초문화재단,초등학생 이상 관람가능,R석 2만원 S석 1만5천원,02-3477-2805,,...,2026-04-09,기관,2026-04-25 00:00:00.0,2026-04-25 00:00:00.0,기타,126.9912424758,37.4988344628,유료,https://culture.seoul.go.kr/culture/culture/cu...,토 15:00

In [ ]:
ALLOWED_GU = ['강남구', '서초구', '마포구', '성동구', '송파구', '동대문구']
df = df[df['GUNAME'].isin(ALLOWED_GU)]
print(df['GUNAME'].value_counts())

GUNAME
강남구     8
마포구     7
송파구     7
서초구     5
성동구     3
동대문구    2
Name: count, dtype: int64

In [ ]:
df = df.drop(columns=['ORG_NAME','USE_TRGT','USE_FEE','INQUIRY','PLAYER','RGSTDATE','TICKET','THEMECODE','DATE','LOT','LAT','IS_FREE','HMPG_ADDR','PRO_TIME'	])

In [ ]:
df = df.drop(columns=['ORG_LINK','MAIN_IMG'])

In [ ]:
df = df.drop(columns=['ETC_DESC'])

In [ ]:
df = df.drop(columns=['PROGRAM'])

In [ ]:
df = df.drop(columns=['CODENAME'])

In [ ]:
display(df)

,GUNAME,TITLE,PLACE,STRTDATE,END_DATE
0,강남구,2026 핸드아티코리아,코엑스전시장 B홀,2026-08-13 00:00:00.0,2026-08-16 00:00:00.0
1,강남구,해외바이어가 직접 찾는 글로벌 전시회 [2026 인터참코리아] InterCHARM ...,"코엑스 A홀, C홀",2026-07-01 00:00:00.0,2026-07-03 00:00:00.0
2,강남구,[GS아트센터] 양인모 X 김치앤칩스,GS아트센터,2026-06-30 00:00:00.0,2026-06-30 00:00:00.0
3,강남구,[GS아트센터] NDT 1 - 필름 스크리닝 [미스트],GS아트센터,2026-06-28 00:00:00.0,2026-06-28 00:00:00.0
4,강남구,[GS아트센터] 다미앵 잘레 X 코헤이 나와 [프리즘],GS아트센터,2026-06-28 00:00:00.0,2026-06-28 00:00:00.0
5,마포구,[마포문화재단] 2026 MAC 모닝 콘서트 ＃4,마포아트센터 아트홀맥,2026-06-24 00:00:00.0,2026-06-24 00:00:00.0
7,마포구,[마포문화재단] 2026 M 아티스트 [선율 피아노 리사이틀Ⅰ],마포아트센터 아트홀맥,2026-06-04 00:00:00.0,2026-06-04 00:00:00.0
8,마포구,[마포문화재단] 연극 [미미의 미미한 연애],마포아트센터 플레이맥,2026-06-03 00:00:00.0,2026-06-07 00:00:00.0
10,서초구,[서울시립교향악단] 2026 서울시향 마르쿠스 슈텐츠와 바딤 글루즈만 ②,예술의전당 콘서트홀,2026-05-29 00:00:00.0,2026-05-29 00:00:00.0
12,송파구,[서울시립교향악단] 2026 서울시향 마르쿠스 슈텐츠와 바딤 글루즈만 ①,롯데콘서트홀,2026-05-28 00:00:00.0,2026-05-28 00:00:00.0
13,강남구,GS아트센터 x 국립심포니오케스트라 라이브 애니메이션 시네스테틱스 [피터와 늑대 &...,GS아트센터,2026-05-28 00:00:00.0,2026-05-28 00:00:00.0
16,마포구,[마포문화재단] M 마티네 [2026 MAC 모닝 콘서트 ＃3],마포아트센터 아트홀맥,2026-05-27 00:00:00.0,2026-05-27 00:00:00.0
25,강남구,제46회 전통공예명품전,국가무형유산전수교육관 3층 전시장 「올」,2026-05-14 00:00:00.0,2026-05-22 00:00:00.0
28,송파구,[한성백제박물관] 역사를 알기 쉽게 천천히 배우고 싶은 초등학생을 위한 [신비한 유...,한성백제박물관 교육실,2026-05-13 00:00:00.0,2026-06-24 00:00:00.0
30,동대문구,[동대문문화재단] 브런치 콘서트 아트리움 - 국립오페라단: 국립오페라스튜디오,선농단역사문화관 지하 3층 중정,2026-05-13 00:00:00.0,2026-05-13 00:00:00.0
32,송파구,"[서울백제어린이박물관] 초등 2-3학년 학급 대상 [어린이백제연구소2] 옛날 도구,...","서울백제어린이박물관(교육실, 전시실)",2026-05-12 00:00:00.0,2026-06-10 00:00:00.0
40,서초구,[서울시립교향악단] 2026 서울시향 김선욱과 알리스 사라 오트 ②,예술의전당 콘서트홀,2026-05-09 00:00:00.0,2026-05-09 00:00:00.0
44,송파구,[서울시립교향악단] 2026 서울시향 김선욱과 알리스 사라 오트 ①,롯데콘서트홀,2026-05-08 00:00:00.0,2026-05-08 00:00:00.0
50,강남구,[강남구 평생학습센터] 유럽 4개국 문화원과 함께하는 [세계인의날 특강],논현글로벌평생학습센터 3층 3강의실,2026-05-06 00:00:00.0,2026-05-08 00:00:00.0
58,송파구,[서울시립교향악단] 2026 서울시향 키즈 콘서트 - 클래식 음악 여행,롯데콘서트홀,2026-05-02 00:00:00.0,2026-05-02 00:00:00.0
60,성동구,2026 서울국제정원박람회,서울숲 일대,2026-05-01 00:00:00.0,2026-10-27 00:00:00.0
62,마포구,[마포문화재단] 2026 마포문화재단 가족·어린이 축제 [해피 마포 와글와글] 뮤지...,마포아트센터 아트홀맥,2026-05-01 00:00:00.0,2026-05-24 00:00:00.0
65,서초구,김정연 바이올린 독주회,예술의전당 IBK 기업은행챔버홀,2026-05-01 00:00:00.0,2026-05-01 00:00:00.0
68,마포구,"[마포구립서강도서관] 4-6월/어린이강좌 [우리 함께 동화읽을래?, 동화동무씨동무]",마포구립서강도서관 3층 세미나실,2026-04-29 00:00:00.0,2026-06-24 00:00:00.0
71,송파구,[서울책보고] 첫눈토크#4 [도시는 사람을 만들고 사람은 도시를 만든다],서울책보고 라운지,2026-04-29 00:00:00.0,2026-04-29 00:00:00.0
75,마포구,[PLATFORM P 교육 프로그램] 변화하는 독자층을 위한 출판 전략 - 큰글자책...,플랫폼 P 2층 다목적실,2026-04-29 00:00:00.0,2026-04-29 00:00:00.0
79,송파구,[한성백제박물관] 2026년 상반기 성인 대상 [서울 고대유적 탐방],"한성백제박물관, 몽촌토성, 풍납동토성, 석촌동고분군 일대",2026-04-28 00:00:00.0,2026-06-11 00:00:00.0
86,서초구,[살롱클래식] 한솔빈 바이올린 독주회,라율아트홀,2026-04-27 00:00:00.0,2026-04-27 00:00:00.0
88,성동구,[성동구립도서관] 4월 영어스토리텔링 수업,성동구립도서관,2026-04-26 00:00:00.0,2026-04-26 00:00:00.0
90,성동구,IAN KIM 피아노 리사이틀 - 절망에서 기쁨으로,서울숲 STUDIO301,2026-04-25 00:00:00.0,2026-05-30 00:00:00.0
92,동대문구,[동대문문화재단] 2026년 생생 국가유산 사업 [지구를 지키는 선농단] - 어린이...,선농단역사문화관 및 선농단역사공원,2026-04-25 00:00:00.0,2026-05-23 00:00:00.0
99,서초구,[서초문화재단] 2026 서리풀 작곡가 탐구 시리즈 [고향에서 세계로 : 드보르작의...,반포심산아트홀,2026-04-25 00:00:00.0,2026-04-25 00:00:00.0